mars-rover-app/config/routes.rb
Rover::Application.routes.draw do

  devise_for :users

  get "home/index"

  resources :grids do
     resources :shuttles
  end

  root :to => "home#index"

end

mars-rover-app/app/models/grid.rb
class Grid < ActiveRecord::Base
   	has_many :shuttles
	validates :x_axis, :y_axis, :presence => true, :inclusion => { :in => 1..21, :message => ": Please enter values between 1 and 21 only."}, :numericality => {:only_integer => :true, :message => ": Please enter a integer value only"}
	validates :description, :length => {:minimum => 4, :maximum => 30 }
end

mars-rover-app/app/models/shuttle.rb
#Shuttle can only move 5 blocks
#class FiveBlocksOnlyValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     if (target_x_axis - landing_x_axis) OR (target_y_axis - landing_y_axis) > 5
#	record.errors[attribute] = ": Rovers can only travel for 5 blocks."
#     end
#   end
#end

#Shuttle can't move diagonally
#class DiagonalValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     if (target_x_axis - landing_x_axis) OR (target_y_axis - landing_y_axis) == 0
#      if (target_x_axis - landing_x_axis) OR (target_y_axis - landing_y_axis) == 1
#	record.errors[attribute] = ": Rovers can't move diagonally."
#      end
#     end
#   end
#end

#Has to land in the grid
#class LandInsideGridValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     if (landing_x_axis > x_axis) OR (landing_y_axis > y_axis)
#	record.errors[attribute] = ": Rovers can't move diagonally."
#     end
#   end
#end


class Shuttle < ActiveRecord::Base
   belongs_to :grid
   validates :landing_x_axis, :landing_y_axis, :target_x_axis, :target_y_axis, :presence => true, :numericality => {:only_integer => true}
#   validates :target_x_axis, :target_y_axis, :five_blocks_only => true, :diagonal => true
#   validates :landing_x_axis, :landing_y_axis, :land_inside_grid => true
end

mars-rover-app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable#:recoverable, 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

mars-rover-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

mars-rover-app/app/controllers/grids_controller.rb
class GridsController < ApplicationController
before_filter :authenticate_user!
  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grids }
    end
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
    @grid = Grid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/new
  # GET /grids/new.json
  def new
    @grid = Grid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grid }
    end
  end

  # GET /grids/1/edit
  def edit
    @grid = Grid.find(params[:id])
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(params[:grid])

    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render json: @grid, status: :created, location: @grid }
      else
        format.html { render action: "new" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grids/1
  # PUT /grids/1.json
  def update
    @grid = Grid.find(params[:id])

    respond_to do |format|
      if @grid.update_attributes(params[:grid])
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid = Grid.find(params[:id])
    @grid.destroy

    respond_to do |format|
      format.html { redirect_to grids_url }
      format.json { head :ok }
    end
  end
end

mars-rover-app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

mars-rover-app/app/controllers/shuttles_controller.rb
class ShuttlesController < ApplicationController
before_filter :authenticate_user!, :get_grid
  # GET /shuttles
  # GET /shuttles.json
  def index
    @shuttles = @grid.shuttles.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shuttles }
    end
  end

  # GET /shuttles/1
  # GET /shuttles/1.json
  def show
    @shuttle = @grid.shuttles.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shuttle }
    end
  end

  # GET /shuttles/new
  # GET /shuttles/new.json
  def new
    @shuttle = @grid.shuttles.build 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shuttle }
    end
  end

  # GET /shuttles/1/edit
  def edit
    @shuttle = @grid.shuttles.find(params[:id])
  end

  # POST /shuttles
  # POST /shuttles.json
  def create
    @shuttle = @grid.shuttles.build(params[:shuttle])

    respond_to do |format|
      if @shuttle.save
        format.html { redirect_to ([@grid, @shuttle]), notice: 'Shuttle was successfully created.' }
        format.json { render json: @shuttle, status: :created, location: @shuttle }
      else
        format.html { render action: "new" }
        format.json { render json: @shuttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shuttles/1
  # PUT /shuttles/1.json
  def update
    @shuttle = @grid.shuttles.find(params[:id])

    respond_to do |format|
      if @shuttle.update_attributes(params[:shuttle])
        format.html { redirect_to ([@grid, @shuttle]), notice: 'Shuttle was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shuttle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shuttles/1
  # DELETE /shuttles/1.json
  def destroy
    @shuttle = @grid.shuttles.find(params[:id])
    @shuttle.destroy

    respond_to do |format|
      format.html { redirect_to grid_shuttles_url(@grid) }
      format.json { head :ok }
    end
  end

  #adding the before method

private

  def get_grid
     @grid = Grid.find(params[:grid_id])
  end
end

mars-rover-app/app/helpers/application_helper.rb
module ApplicationHelper
end

mars-rover-app/app/helpers/grids_helper.rb
module GridsHelper
end

mars-rover-app/app/helpers/home_helper.rb
module HomeHelper
end

mars-rover-app/app/helpers/shuttles_helper.rb
module ShuttlesHelper
end

mars-rover-app/app/views/grids/_form.html.erb
<%= simple_form_for(@grid) do |f| %>
  <%= f.input :x_axis %>
  <%= f.input :y_axis %>
  <%= f.input :description, :rows => 4 %>  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

mars-rover-app/app/views/grids/edit.html.erb
<h1>Editing grid</h1>

<%= render 'form' %>

<%= link_to 'Show', @grid, :class => 'btn btn-mini' %> |
<%= link_to 'Back', grids_path, :class => 'btn btn-mini' %>

mars-rover-app/app/views/grids/index.html.erb
<h1>Listing grids</h1>

<table class="table table-striped">
  <tr>
    <th>X axis</th>
    <th>Y axis</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grids.each do |grid| %>
  <tr>
    <td><%= grid.x_axis %></td>
    <td><%= grid.y_axis %></td>
    <td><%= grid.description %></td>
    <td><%= link_to 'Show', grid, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_grid_path(grid), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', grid, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grid', new_grid_path, :class => 'btn btn-primary' %>

mars-rover-app/app/views/grids/new.html.erb
<h1>New grid</h1>

<%= render 'form' %>

<%= link_to 'Back', grids_path, :class => 'btn btn-mini' %>

mars-rover-app/app/views/grids/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover">
    <tr>
      <th>X axis</th>
      <th>Y axis</th>
      <th>Description</th>
    </tr>
  <tbody>
    <tr>
      <td><%= @grid.x_axis %></td>
      <td><%= @grid.y_axis %></td>
      <td><%= @grid.description %></td>
    </tr>
  </tbody>
</table>

  <b>Shuttles:</b>
<table class="table table-bordered">
    <tr>
      <th>Landing position</th>
      <th>Target position</th>
    </tr>
  <tbody>
    <% @grid.shuttles.each do |s| %>
    <tr>

      <td>
      <%= link_to s.landing_x_axis, [s.grid, s] %>,<%= s.landing_y_axis %>
      </td>
      <td>
      <%= link_to s.target_x_axis, [s.grid, s] %>,<%= s.target_y_axis %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_grid_path(@grid), :class => 'btn btn-mini' %> |
<%= link_to 'Back', grids_path, :class => 'btn btn-mini' %>
<%= link_to 'New Shuttle', new_grid_shuttle_path(@grid), :class => 'btn btn-primary' %>

mars-rover-app/app/views/home/index.html.erb
<h2>Hello</hello>
<%= link_to "Grids", grids_path %>

mars-rover-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rover</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Mars Exploration</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Grids", grids_path %></li>
          <li><%= link_to "Get Help" %></li>
          <li><%= link_to "Previous Missions" %></li>
          <li><%= link_to "Report a bug" %></li>
        </ul>
	  
		<% if user_signed_in? %>
		  Logged in as <strong><%= current_user.email %></strong>.
		  <%= link_to 'Edit profile', edit_user_registration_path %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path %> |
		  <%= link_to "Login", new_user_session_path %>
		<% end %>
          
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
      <h2>About Us</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
    </div>
  </div>
</div>
</body>
</html>

mars-rover-app/app/views/shuttles/_form.html.erb
<%= simple_form_for([@grid, @shuttle]) do |f| %>

  <%= f.input :landing_x_axis %>
  <%= f.input :landing_y_axis %>
  <%= f.input :target_x_axis %>
  <%= f.input :target_y_axis %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary'  %>
  </div>
<% end %>

mars-rover-app/app/views/shuttles/edit.html.erb
<h1>Editing shuttle</h1>

<%= render 'form' %>

<%= link_to 'Show', [@grid, @shuttle], :class => 'btn btn-mini' %> |
<%= link_to 'Back', grid_shuttles_path(@grid), :class => 'btn btn-mini' %>

mars-rover-app/app/views/shuttles/index.html.erb
<h1>Listing shuttles</h1>

<table class="table table-striped">
  <tr>
    <th>Landing x axis</th>
    <th>Landing y axis</th>
    <th>Target x axis</th>
    <th>Target y axis</th>
    <th>Grid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shuttles.each do |shuttle| %>
  <tr>
    <td><%= shuttle.landing_x_axis %></td>
    <td><%= shuttle.landing_y_axis %></td>
    <td><%= shuttle.target_x_axis %></td>
    <td><%= shuttle.target_y_axis %></td>
    <td><%= shuttle.grid.x_axis %>,<%= shuttle.grid.y_axis %></td>
    <td><%= link_to 'Show', [@grid, shuttle], :class => 'btn btn-mini'  %></td>
    <td><%= link_to 'Edit', edit_grid_shuttle_path(@grid, shuttle), :class => 'btn btn-mini'  %></td>
    <td><%= link_to 'Destroy', [@grid, shuttle], confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini'  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shuttle', new_grid_shuttle_path, :class => 'btn btn-primary' %>

mars-rover-app/app/views/shuttles/new.html.erb
<h1>New shuttle</h1>

<%= render 'form' %>

<%= link_to 'Back', grid_shuttles_path(@grid), :class => 'btn btn-mini' %>

mars-rover-app/app/views/shuttles/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-hover">
    <tr>
      <th>Landing x axis</th>
      <th>Landing y axis</th>
      <th>Target x axis</th>
      <th>Target y axis</th>
    </tr>
  <tbody>
    <tr>
      <td><%= @shuttle.landing_x_axis %></td>
      <td><%= @shuttle.landing_y_axis %></td>
      <td><%= @shuttle.target_x_axis %></td>
      <td><%= @shuttle.target_y_axis %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_grid_shuttle_path(@grid, @shuttle), :class => 'btn btn-mini' %> |
<%= link_to 'Back', grid_shuttles_path(@grid), :class => 'btn btn-mini' %>